package com.example.astrolingo.apdapter.home.game_hangman;

import java.util.Arrays;
import java.util.List;

public class GameConstants {

//    public static final List<String> words = Arrays.asList(
//            "Afghanistan",
//            "Albania",
//            "Algeria",
//            "American/Samoa",
//            "Andorra",
//            "Angola",
//            "Anguilla",
//            "Antarctica",
//            "Antigua/and/Barbuda",
//            "Argentina",
//            "Armenia",
//            "Aruba",
//            "Australia",
//            "Austria",
//            "Azerbaijan",
//            "Bahamas",
//            "Bahrain",
//            "Bangladesh",
//            "Barbados",
//            "Belarus",
//            "Belgium",
//            "Belize",
//            "Benin",
//            "Bermuda",
//            "Bhutan",
//            "Bolivia",
//            "Bosnia/and/Herzegovina",
//            "Botswana",
//            "Bouvet/Island",
//            "Brazil",
//            "British/Indian/Ocean/Territory",
//            "Brunei/Darussalam",
//            "Bulgaria",
//            "Burkina/Faso",
//            "Burundi",
//            "Cambodia",
//            "Cameroon",
//            "Canada",
//            "Cape/Verde",
//            "Cayman/Islands",
//            "Central/African/Republic",
//            "Chad",
//            "Chile",
//            "China",
//            "Christmas/Island",
//            "Colombia",
//            "Comoros",
//            "Congo",
//            "Cook/Islands",
//            "Costa/Rica",
//            "Cuba",
//            "Cyprus",
//            "Czech/Republic",
//            "Denmark",
//            "Djibouti",
//            "Dominica",
//            "Dominican/Republic",
//            "East/Timor",
//            "Ecuador",
//            "Egypt",
//            "El/Salvador",
//            "Equatorial/Guinea",
//            "Eritrea",
//            "Estonia",
//            "Ethiopia",
//            "Faroe/Islands",
//            "Fiji",
//            "Finland",
//            "France",
//            "France",
//            "Metropolitan",
//            "French/Guiana",
//            "French/Polynesia",
//            "French/Southern/Territories",
//            "Gabon",
//            "Gambia",
//            "Georgia",
//            "Germany",
//            "Ghana",
//            "Gibraltar",
//            "Greece",
//            "Greenland",
//            "Grenada",
//            "Guadeloupe",
//            "Guam",
//            "Guatemala",
//            "Guinea",
//            "Guinea-Bissau",
//            "Guyana",
//            "Haiti",
//            "Heard/and/McDonald/Islands",
//            "Honduras",
//            "Hong/Kong",
//            "Hungary",
//            "Iceland",
//            "India",
//            "Indonesia",
//            "Iran",
//            "Iraq",
//            "Ireland",
//            "Israel",
//            "Italy",
//            "Jamaica",
//            "Japan",
//            "Jordan",
//            "Kazakhstan",
//            "Kenya",
//            "Kiribati",
//            "Kuwait",
//            "Kyrgyzstan",
//            "Laos",
//            "Latvia",
//            "Lebanon",
//            "Lesotho",
//            "Liberia",
//            "Libya",
//            "Liechtenstein",
//            "Lithuania",
//            "Luxembourg",
//            "Macau",
//            "Macedonia",
//            "Madagascar",
//            "Malawi",
//            "Malaysia",
//            "Maldives",
//            "Mali",
//            "Malta",
//            "Marshall Islands",
//            "Martinique",
//            "Mauritania",
//            "Mauritius",
//            "Mayotte",
//            "Mexico",
//            "Micronesia",
//            "Moldova",
//            "Monaco",
//            "Mongolia",
//            "Montserrat",
//            "Morocco",
//            "Mozambique",
//            "Myanmar",
//            "Namibia",
//            "Nauru",
//            "Nepal",
//            "Netherlands",
//            "New/Caledonia",
//            "New/Zealand",
//            "Nicaragua",
//            "Niger",
//            "Nigeria",
//            "Niue",
//            "Norfolk/Island",
//            "Northern/Mariana/Islands",
//            "Norway",
//            "Oman",
//            "Pakistan",
//            "Palau",
//            "Panama",
//            "Papua/New/Guinea",
//            "Paraguay",
//            "Peru",
//            "Philippines",
//            "Pitcairn",
//            "Poland",
//            "Portugal",
//            "Puerto/Rico",
//            "Qatar",
//            "Reunion",
//            "Romania",
//            "Russian/Federation",
//            "Rwanda",
//            "Saint/Kitts/and/Nevis",
//            "Saint/Lucia",
//            "Saint/Vincent/and/The/Grenadines",
//            "Samoa",
//            "San/Marino",
//            "Sao/Tome/and/Principe",
//            "Saudi/Arabia",
//            "Senegal",
//            "Seychelles",
//            "Sierra/Leone",
//            "Singapore",
//            "Slovak/Republic",
//            "Slovenia",
//            "Solomon/Islands",
//            "Somalia",
//            "South/Africa",
//            "Spain",
//            "Sri/Lanka",
//            "Sudan",
//            "Suriname",
//            "Svalbard/and/Jan/Mayen/Islands",
//            "Swaziland",
//            "Sweden",
//            "Switzerland",
//            "Syria",
//            "Taiwan",
//            "Tajikistan",
//            "Tanzania",
//            "Thailand",
//            "Togo",
//            "Tokelau",
//            "Tonga",
//            "Trinidad/and/Tobago",
//            "Tunisia",
//            "Turkey",
//            "Turkmenistan",
//            "Turks/and/Caicos/Islands",
//            "Tuvalu",
//            "Uganda",
//            "Ukraine",
//            "United/Arab/Emirates",
//            "US/Minor/Outlying/Islands",
//            "Uruguay",
//            "Uzbekistan",
//            "Vanuatu",
//            "Venezuela",
//            "Viet/Nam",
//            "Wallis/and/Futuna/Islands",
//            "Western/Sahara",
//            "Yemen",
//            "Yugoslavia",
//            "Zaire",
//            "Zambia",
//            "Zimbabwe"
//    );
    public static final List<String> words = Arrays.asList(
            "abide",
            "abolish",
            "abundant",
            "access",
            "accommodate",
            "accompany",
            "accomplish",
            "accordingly",
            "account",
            "accuracy",
            "accurate",
            "accustom",
            "achieve",
            "acknowledge",
            "acquire",
            "activate",
            "adapt",
            "additionally",
            "adequate",
            "adjacent",
            "adjust",
            "administer",
            "advantage",
            "advertise",
            "advice",
            "advocate",
            "affect",
            "affordable",
            "agency",
            "agenda",
            "aggressive",
            "agreeable",
            "aid",
            "aim",
            "airline",
            "alarm",
            "allocate",
            "allow",
            "alter",
            "alternative",
            "amend",
            "amount",
            "analyze",
            "annual",
            "anticipate",
            "anxiety",
            "apology",
            "apparent",
            "appeal",
            "applicant",
            "appoint",
            "appraise",
            "appreciate",
            "approach",
            "appropriate",
            "approve",
            "approximate",
            "arise",
            "arrange",
            "article",
            "aspect",
            "assemble",
            "assess",
            "asset"
    );

}
